version: 0.0
os: linux
files:
  - source: /.war
    destination: /usr/share/apache-tomcat-9.0.63/webapps/
    
file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: ./scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: ./scripts/stop_server.sh
      timeout: 300
      runas: root
