---
- name: install tomcat server
  hosts: all
  become: true
  tasks:
  - name: download tomcat server packages
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.68/bin/apache-tomcat-9.0.68.tar.gz
      dest: /usr/local
  - name: extract tomcat packages
    unarchive:
      src: /usr/local/apache-tomcat-9.0.68.tar.gz
      dest: /usr/local
      remote_src: yes
  - name: start tomcat services
    shell: nohup /usr/local/apache-tomcat-9.0.68/bin/startup.sh
  - name: Deploy static website
    copy:
      src: /var/lib/jenkins/workspace/demo/target/LoginWebApp-1.war
      dest: /usr/local/apache-tomcat-9.0.68/webapps
