---
# tasks file for tomcat
- name: Download Open JDK
  become: yes
  yum: 
   name: java
   state: present
- name: Download tomcat
  get_url:
   url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.70/bin/apache-tomcat-9.0.70.tar.gz
   dest: /opt
- name: Extract tomcat
  unarchive:
   src: /opt/apache-tomcat-9.0.70.tar.gz
   dest: /opt
   remote_src: true
- name: remove directory tomcat
  become: yes
  file:
   path: /opt/tomcat
   state: absent
- name: create directory tomcat
  become: yes
  file:
   path: /opt/tomcat
   state: directory
- name: move apache tomcat to tomcat directory
  shell: "mv /opt/apache-tomcat-9.0.70 /opt/tomcat/"
- name: changing ownership permissions of /bin/*.sh files
  shell: "chmod +x /opt/tomcat/apache-tomcat-9.0.70/bin/*.sh"
- name: Changing tomcat port
  template: 
   src: server.xml.j2
   dest: /opt/tomcat/apache-tomcat-9.0.70/conf/server.xml
   remote_src: false
- name: Updating users and role
  template: 
   src: tomcat-users.xml.j2
   dest: /opt/tomcat/apache-tomcat-9.0.70/conf/tomcat-users.xml
   remote_src: false
- name: Updating context.xml restriction
  template: 
   src: context.xml.j2
   dest: /opt/tomcat/apache-tomcat-9.0.70/webapps/manager/META-INF/context.xml
   remote_src: false
- name: Download war file from Nexus
  get_url:
   url: 'http://3.110.162.149:8081/repository/demo/com/ltidevops/LoginWebApp/1/LoginWebApp-1.war'
   dest: /opt/tomcat/apache-tomcat-9.0.70/webapps/ 
   url_username: admin  
   url_password: admin123
- name: start tomcat
  shell: sh /opt/tomcat/apache-tomcat-9.0.70/bin/catalina.sh stop && nohup /opt/tomcat/apache-tomcat-9.0.70/bin/catalina.sh start
