---
# tasks file for tomcat
- name: Download Open JDK
  become: yes
  yum: 
   name: java
   state: present
- name: Create the group
  become: yes
  group:
   name: tomcat
   state: present
- name: Create the user
  become: yes
  user: 
   name: tomcat
   state: present
- name: Create directory /opt/tomcat8
  become: yes
  file:
   path: /opt/tomcat8
   state: directory
   mode: 0755
   owner: tomcat
   group: tomcat
- name: Download and extract tomcat
  get_url:
   url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.84/src/apache-tomcat-8.5.84-src.tar.gz
   dest: /opt/tomcat8
- name: Download and extract tomcat
  unarchive:
   src: /opt/tomcat8/apache-tomcat-8.5.84-src.tar.gz
   dest: /opt/tomcat8
   remote_src: true
- name: Change ownership of tomcat directory
  file:
   path: /opt/tomcat8
   owner: tomcat
   group: tomcat
   mode: 0755
   state: directory
- name: Change tomcat url name to tomcat8
  become: yes
  become_user: tomcat
  shell: "mv /opt/tomcat8/apache*/* /opt/tomcat8"
- name: Download war file from Nexus
  become: yes
  copy: 
   src: "{{URL_ART}}"
   dest: /opt/tomcat8/webapps/ 
- name: enable tomcat startup
  systemd: 
   name: tomcat
   enabled: yes
   state: restarted
   become: true
