---
# tasks file for tomcat
- name: Download Open JDK
  become: yes
  yum: 
   name: java
   state: present
- name: Create the group
  become: yes
  group:
   name: tomcat
   state: present
- name: Create the user
  become: yes
  user: 
   name: tomcat
   state: present
- name: Create directory /opt/tomcat8
  become: yes
  file:
   path: /opt/tomcat8
   state: directory
   mode: 0777
   owner: tomcat
   group: tomcat
- name: Download tomcat
  get_url:
   url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.84/src/apache-tomcat-8.5.84-src.tar.gz
   dest: /opt/tomcat8
- name: Extract tomcat
  unarchive:
   src: /opt/tomcat8/apache-tomcat-8.5.84-src.tar.gz
   dest: /opt/tomcat8
   remote_src: true
- name: Change ownership of tomcat directory
  file:
   path: /opt/tomcat8
   owner: tomcat
   group: tomcat
   mode: 0777
   state: directory
- name: Download war file from Nexus
  maven_artifact: 
   username: "{{nexusername}}"
   password: "{{nexpwd}}"
   artifact_id: "{{aid}}"
   group_id: "{{gid}}"
   state: present
   src: "{{URL_ART}}"
   extension: war
   version: "1"
   dest: /opt/tomcat8/apache-tomcat-8.5.84-src/webapps/ 
   remote_src: yes
- name: enable tomcat startup
  systemd: 
   name: tomcat
   enabled: yes
   state: restarted
   become: true
