---
# tasks file for tomcat
- name: Download Open JDK
  become: yes
  yum: 
   name: java
   state: present
- name: Download tomcat
  get_url:
   url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.84/src/apache-tomcat-8.5.84-src.tar.gz
   dest: /usr/local
- name: Extract tomcat
  unarchive:
   src: /usr/local/apache-tomcat-8.5.84-src.tar.gz
   dest: /usr/local
   remote_src: true
- name: Download war file from Nexus
  get_url:
   url: 'http://13.232.97.77:8081/repository/demo/com/ltidevops/LoginWebApp/1/LoginWebApp-1.war'
   dest: /usr/local/apache-tomcat-8.5.84-src/webapps/ 
   url_username: admin  
   url_password: admin123
- name: start tomcat
  shell: nohup /usr/local/apache-tomcat-8.5.84-src/bin/catalina.sh & 
