replicaCount: 2

image:
  name: firstimg
  repository: https://hub.docker.com/repository/docker/signin/helm
  pullPolicy: IfNotPresent


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

container:
  port: 9090

service:
  protocol: TCP
  type: ClusterIP
  port: 9090
