replicaCount: 2

image:
  name: firstimg
  repository: docker.io/signin/helm
  tag: "latest"
  pullPolicy: IfNotPresent


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

container:
  port: 9090

service:
  protocol: TCP
  type: LoadBalancer
  port: 9090
